server:
  port: 9000

spring:
  jpa:
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    open-in-view: false
  datasource:
    dirver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mysql://${host_ip}:${port}/scheme?characterEncoding-UDF-8&serverTimezone=UTC
    username: root
    password: 1234

logging:
  level:
    root: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type: trace
    org.hibernate.type.descriptor.sql: trace